SERVICE_NAME="REPLACE_SERVICE_NAME"

SERVICE_VERSION="1.0.0"

ENV="local"

PORT=9100

PG_HOST="localhost"

PG_PORT=5432

PG_USER="postgres"

PG_PASS="password"

PG_DB="postgres"

MY_SERVICE="localhost:10009"